spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javastack
    username: root
    password: 123456
    druid:
      one:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/javastack
        username: root
        password: 123456
        initial-size: 10
        max-active: 10
        min-idle: 5
        max-wait: 60000
      two:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/javastack
        username: root
        password: 123456
        initial-size: 10
        max-active: 10
        min-idle: 5
        max-wait: 60000
      web-stat-filter:
        enabled: true
        url-pattern: /
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: root
        login-password: 123456
