server:
  port: 8001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javastack
    username: root
    password: 12345678

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.javastack.springboot.mybatis.entity